//
// Copyright (C) 2016 Xillio (support@xillio.com)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= Introduction

Data transformation is a complex process, which becomes progressively more difficult as content grows. To make this
problem easier we decided to transform content from and to the UDM. The goal of this model is to
make it easier to transform data, especially to and from different source systems. This library makes it possible to
map data to and from this model in a standardized way. This document is to help anyone willing to work with this
library, since it will explain on how to use it and how it works.
