= How it works

== Running Build.xill
1. The getMappings function is called.
This function recursively iterates over all folders in the root of the project. If the name of a folder is '_mappings_' all the paths to the robots inside of that folder are added to a list.

2. The generateMapper function is called.
This function reads the contents of the `_MapperTemplate` robot. This is the template for the mapper.
It contains three placeholders (`INCLUDE_MAPPING`, `IF_MAPPING`, `TYPE_MAPPING`) that will be replaced by the strings constructed in the following steps.

3. Three functions are called for each robot found in step 1.  The result of each function is appended to the corresponding variable.
    * The `addIncludeStatement` function append to the `includeStatements` variable. +
    * The `addIfStatement` function append to the `ifStatements` variable. +
    * The `addTypeStatement` function append to the  `typeStatements` variable. +


4. The saveMapper function is called. This will replace the placeholders in the template from step 2 with the variables from step 3.
   * `INCLUDE_MAPPING` is replaced with the `includeStatements` variable +
   * `IF_MAPING` is replaced with the `ifStatements` variable +
   * `TYPE_MAPPING` is replaced with the `typeStatements` variable +

5. The resulting string will be saved as `Mapper.xill` in root/config/

== Mapper functions

The Mapper robot has two functions: mapObject and mapSourceToTargetType.

=== mapObject

function mapObject(object, contentType);

This function will map the object (first parameter) to the specified contentType (second parameter).

The function contains an if-statement for each contentType it could find during the creation of the Mapper.
If the provided contentType is equal to one of these contentTypes then it will run the following code:

----
var parentContentType = getExampleParentTemplate();        // <1>
if(parentContentType != null && parentContentType != "") { // <2>
    foreach(type in parentContentType) {                   // <3>
        var parent = mapObject(object, type);
        result += mapExample(parent, object);
    }
} else {
    result = mapExample({}, object);                       //<4>
}
----

<1> Call the `getExampleParentTemplate` function from the included `Example.xill`
<2> Check if the example mapping has a parentContentType
<3> Iterate over these parentContentTypes and call mapObject on these parent before calling mapExample
<4> The mapping does not have a parent so just call the mapExample function.

=== mapSourceToTargetType

mapSourceToTargetType(contentType, context);

This function compares the provided contentType to the output of `getSourceType` function of each mapping.
If the provided contentType is equal to one of these then the contentType of this mapping is returned.